### ISSUE TITLE
Error importing libs

### ISSUE THREAD

**Issue by secco04** [grjw/ExpressVPNForKodi#1]
Hi today I tried to install this add on but I get:

Error Type: <type 'exceptions.ImportError'>
Error Contents: No module named lib.expressvpn

In Ressources the files are missing

**Comment by no1be4me** [comment]
I installed it as well and got this same error.

**Comment by grjw** [comment]
Many apologies for the long delay at looking at this. The lib files were excluded by git so they weren't committed. I have committed them now along with another fix so it should work if you fork/pull the repo again. Sorry about that!
